sudoe: required
language: generic

services:
  - docker

before_install:
  - docker build -t pristine/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pristine/react-test npm test

after_success:
  - docker build -t pristine/multi-client ./client
  - docker build -t pristine/multi-nginx ./nginx
  - docker build -t pristine/multi-server ./server
  - docker build -t pristine/multi-worker ./worker
  # Log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push pristine/multi-client
  - docker push pristine/multi-nginx
  - docker push pristine/multi-server
  - docker push pristine/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'eu-west-2'
  app: 'pristine-multiservices'
  env: 'PristineMultiServices-env'
  bucket_name: 'elasticbeanstalk-eu-west-2-165893722651'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY