sudoe: required
services:
  - docker

before_install:
  - docker build -t iceshop/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true iceshop/react-test npm test -- --coverage

after_success:
  - docker build -t will/multi-client ./client
  - docker build -t will/multi-nginx ./nginx
  - docker build -t will/multi-server ./server
  - docker build -t will/multi-worker ./worker
  # Log in to the docker cli